"""empty message

Revision ID: 2a240b6176ef
Revises: ff773708e658
Create Date: 2022-08-13 02:06:08.103067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a240b6176ef'
down_revision = 'ff773708e658'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('venues_area')
    op.drop_table('artist_area')
    op.add_column('Artist', sa.Column('area_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'Artist', 'areas', ['area_id'], ['id'])
    op.add_column('Venue', sa.Column('area_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'Venue', 'areas', ['area_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Venue', type_='foreignkey')
    op.drop_column('Venue', 'area_id')
    op.drop_constraint(None, 'Artist', type_='foreignkey')
    op.drop_column('Artist', 'area_id')
    op.create_table('artist_area',
    sa.Column('artist_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('area_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], name='artist_area_area_id_fkey'),
    sa.ForeignKeyConstraint(['artist_id'], ['Artist.id'], name='artist_area_artist_id_fkey'),
    sa.PrimaryKeyConstraint('artist_id', 'area_id', name='artist_area_pkey')
    )
    op.create_table('venues_area',
    sa.Column('venue_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('area_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], name='venues_area_area_id_fkey'),
    sa.ForeignKeyConstraint(['venue_id'], ['Venue.id'], name='venues_area_venue_id_fkey'),
    sa.PrimaryKeyConstraint('venue_id', 'area_id', name='venues_area_pkey')
    )
    # ### end Alembic commands ###
